window.SPANISH_GYM_CONTENT = {
  "1": {
    vocab: {
      "Begrüßen & reagieren": [["¡Hola!", "Hallo!", "core"], ["¿Qué tal?", "Wie geht's?", "core"], ["muy bien", "sehr gut", "core"], ["bien", "gut", "core"], ["más o menos", "mehr oder weniger", "core"], ["mal", "schlecht", "core"], ["gracias", "danke", "core"], ["encantado/a", "erfreut", "core"], ["mucho gusto", "freut mich / sehr angenehm", "core"], ["¡Buenos días!", "Guten Morgen!", "core"], ["¡Buenas tardes!", "Guten Tag / Guten Abend!", "core"], ["¡Buenas noches!", "Guten Abend / Gute Nacht!", "core"], ["¡Hasta luego!", "Bis später!", "core"], ["¡Adiós!", "Auf Wiedersehen!", "core"]],
      "Sich vorstellen": [["me llamo", "ich heiße", "core"], ["soy", "ich bin", "core"], ["soy de", "ich komme aus", "core"], ["¿Cómo te llamas?", "Wie heißt du?", "core"], ["¿De dónde eres?", "Woher kommst du?", "core"], ["el nombre", "der Vorname / Name", "core"], ["¿Cómo se escribe...?", "Wie schreibt man ...?", "core"], ["el número de teléfono", "die Telefonnummer", "core"], ["el móvil", "das Handy", "core"], ["¿Cuál es tu número de teléfono?", "Wie lautet deine Telefonnummer?", "core"]],
      "Sprachen & Herkunft": [["hablar", "sprechen", "core"], ["el español", "Spanisch", "core"], ["el alemán", "Deutsch", "core"], ["el inglés", "Englisch", "core"], ["un poco (de)", "ein bisschen", "core"], ["también", "auch", "core"], ["¿Qué lenguas hablas?", "Welche Sprachen sprichst du?", "core"], ["España", "Spanien", "extension"], ["Alemania", "Deutschland", "extension"], ["Perú", "Peru", "extension"], ["Francia", "Frankreich", "extension"]],
      "Schule, Studium & Arbeit": [["estudiar", "lernen / zur Schule gehen / studieren", "core"], ["trabajar", "arbeiten", "core"], ["el instituto", "die weiterführende Schule", "core"], ["la universidad", "die Universität", "core"], ["la clase", "die Klasse / der Unterricht", "core"], ["el examen", "die Prüfung", "core"], ["la biblioteca", "die Bibliothek", "core"], ["el ejercicio", "die Übung", "core"], ["la pregunta", "die Frage", "core"], ["el texto", "der Text", "core"], ["leer", "lesen", "core"], ["escribir", "schreiben", "core"], ["aprender", "lernen", "core"], ["comprender", "verstehen", "core"], ["necesitar", "brauchen", "core"], ["la ayuda", "die Hilfe", "core"], ["el ordenador", "der Computer", "core"], ["el programa", "das Programm", "extension"]],
      "Alltag & Verabredung": [["quedar", "sich verabreden", "core"], ["¿Cuándo quedamos?", "Wann treffen wir uns?", "core"], ["mañana", "morgen", "core"], ["ahora", "jetzt", "core"], ["primero", "zuerst", "core"], ["después", "danach / später", "core"], ["juntos/as", "zusammen", "core"], ["de acuerdo", "einverstanden", "core"], ["¡Buena idea!", "Gute Idee!", "core"], ["comer", "essen", "core"], ["tomar", "nehmen / trinken", "core"], ["bailar", "tanzen", "core"], ["descansar", "sich entspannen / ausruhen", "core"], ["comprar", "kaufen", "core"], ["vivir", "leben / wohnen", "core"], ["cerca", "in der Nähe", "core"], ["la cafetería", "die Cafeteria", "core"], ["el restaurante", "das Restaurant", "core"], ["el supermercado", "der Supermarkt", "core"], ["la discoteca", "die Diskothek", "extension"], ["la película", "der Film", "extension"], ["el regalo", "das Geschenk", "extension"]]
    },
    grammar: {
      "Präsens: regelmäßige Verben": [["hablar: yo", "hablo"], ["hablar: nosotros/as", "hablamos"], ["comprender: tú", "comprendes"], ["comprender: ellos/as", "comprenden"], ["vivir: él/ella", "vive"], ["vivir: vosotros/as", "vivís"]],
      "ser": [["yo", "soy"], ["tú", "eres"], ["él/ella/usted", "es"], ["nosotros/as", "somos"], ["vosotros/as", "sois"], ["ellos/ellas/ustedes", "son"]],
      "Verneinung mit no": [["Ich arbeite nicht.", "No trabajo."], ["Ich verstehe nicht.", "No comprendo."], ["Ich spreche kein Deutsch.", "No hablo alemán."]],
      "Artikel & Plural": [["der Freund", "el amigo"], ["die Freundin", "la amiga"], ["ein Freund", "un amigo"], ["eine Freundin", "una amiga"], ["die Freunde", "los amigos"], ["die Freundinnen", "las amigas"], ["die Handys", "los móviles"], ["die Städte", "las ciudades"]],
      "Subjektpronomen": [["ich", "yo"], ["du", "tú"], ["er / sie / Sie", "él / ella / usted"], ["wir", "nosotros/as"], ["ihr", "vosotros/as"], ["sie / Sie", "ellos / ellas / ustedes"]],
      "Fragewörter": [["wie?", "¿cómo?"], ["woher?", "¿de dónde?"], ["wo?", "¿dónde?"], ["was?", "¿qué?"], ["wer?", "¿quién? / ¿quiénes?"], ["wann?", "¿cuándo?"], ["warum?", "¿por qué?"], ["welcher / welche?", "¿cuál? / ¿cuáles?"]]
    }
  },
  "2": {
    vocab: {
      "Familie & Personen": [["la gente", "die Leute", "core"], ["la familia", "die Familie", "core"], ["los padres", "die Eltern", "core"], ["los hermanos", "die Geschwister", "core"], ["el hermano", "der Bruder", "core"], ["la hermana", "die Schwester", "core"], ["los abuelos", "die Großeltern", "core"], ["el abuelo", "der Opa", "core"], ["la abuela", "die Oma", "core"], ["el tío", "der Onkel", "core"], ["la tía", "die Tante", "core"], ["el primo", "der Cousin", "core"], ["la prima", "die Cousine", "core"], ["el mejor amigo / la mejor amiga", "der beste Freund / die beste Freundin", "core"], ["el novio / la novia", "der feste Freund / die feste Freundin", "core"], ["el apellido", "der Nachname", "core"], ["la edad", "das Alter", "core"], ["¿Cuántos años tienes?", "Wie alt bist du?", "core"], ["tengo ... años", "ich bin ... Jahre alt", "core"]],
      "Personen beschreiben": [["guapo/a", "hübsch", "core"], ["simpático/a", "sympathisch", "core"], ["serio/a", "ernst", "core"], ["divertido/a", "lustig", "core"], ["alegre", "fröhlich", "core"], ["tranquilo/a", "ruhig", "core"], ["tímido/a", "schüchtern", "core"], ["interesante", "interessant", "core"], ["aburrido/a", "langweilig", "core"], ["atractivo/a", "attraktiv", "extension"], ["creativo/a", "kreativ", "extension"], ["estricto/a", "streng", "extension"], ["inteligente", "intelligent", "core"], ["mayor", "älter", "core"], ["pequeño/a", "klein", "core"], ["grande", "groß", "core"], ["nuestro/a", "unser/e", "core"], ["vuestro/a", "euer/eure", "extension"]],
      "Mi barrio": [["el barrio", "das Stadtviertel", "core"], ["la calle", "die Straße", "core"], ["la ciudad", "die Stadt", "core"], ["la dirección", "die Adresse", "core"], ["el centro", "das Zentrum", "core"], ["la zona", "die Zone / Gegend", "core"], ["el tráfico", "der Verkehr", "core"], ["el parque", "der Park", "core"], ["el polideportivo", "das Sportzentrum", "core"], ["el centro comercial", "das Einkaufszentrum", "core"], ["la tienda", "der Laden", "core"], ["la panadería", "die Bäckerei", "core"], ["el supermercado", "der Supermarkt", "core"], ["el gimnasio", "das Fitnessstudio", "core"], ["la heladería", "die Eisdiele", "core"], ["el pueblo", "das Dorf", "core"], ["cerca (de)", "in der Nähe (von)", "core"], ["lejos (de)", "weit weg (von)", "core"], ["ruidoso/a", "laut", "core"], ["tranquilo/a", "ruhig", "core"], ["moderno/a", "modern", "core"], ["antiguo/a", "alt / altertümlich", "core"], ["bonito/a", "schön", "core"], ["feo/a", "hässlich", "core"]],
      "Freizeit & Orte": [["el centro cultural", "das Kulturzentrum", "core"], ["el teatro", "das Theater", "core"], ["el cine", "das Kino", "core"], ["el museo", "das Museum", "core"], ["la piscina", "das Schwimmbad", "core"], ["el rocódromo", "die Kletterhalle", "extension"], ["el taller", "der Workshop / die Werkstatt", "extension"], ["el slackline", "Slacklining", "receptive"], ["la visita guiada", "die Führung", "extension"], ["gratis", "kostenlos", "core"], ["el euro", "der Euro", "core"]],
      "Pläne & Vorschläge": [["¿Adónde?", "Wohin?", "core"], ["ir", "gehen / fahren", "core"], ["invitar", "einladen", "core"], ["hay", "es gibt", "core"], ["poder", "können", "core"], ["probar", "probieren / ausprobieren", "core"], ["querer", "wollen", "core"], ["tener que + infinitivo", "etwas tun müssen", "core"], ["hacer", "machen", "core"], ["siempre", "immer", "core"], ["nunca", "nie", "core"], ["a veces", "manchmal", "core"], ["normalmente", "normalerweise", "core"], ["para", "für / um zu", "core"], ["¿Quieres ir...?", "Willst du ... gehen?", "extension"], ["Podemos quedar mañana.", "Wir können uns morgen treffen.", "extension"], ["Tengo que hacer muchas cosas.", "Ich muss viele Dinge machen.", "extension"]]
    },
    grammar: {
      "Gruppenverben e→ie": [["querer: yo", "quiero"], ["querer: tú", "quieres"], ["querer: nosotros/as", "queremos"], ["tener: yo", "tengo"], ["tener: él/ella", "tiene"], ["tener: nosotros/as", "tenemos"]],
      "Adjektive angleichen": [["un libro creativo → zwei Bücher", "dos libros creativos"], ["una película creativa → zwei Filme", "dos películas creativas"], ["un libro interesante → zwei Bücher", "dos libros interesantes"], ["una película interesante → zwei Filme", "dos películas interesantes"]],
      "estar": [["yo", "estoy"], ["tú", "estás"], ["él/ella/usted", "está"], ["nosotros/as", "estamos"], ["vosotros/as", "estáis"], ["ellos/ellas/ustedes", "están"]],
      "hay oder estar": [["___ un supermercado nuevo en el centro.", "Hay"], ["La heladería ___ lejos.", "está"], ["___ muchas tiendas pequeñas.", "Hay"], ["El hotel ___ en esta calle.", "está"]],
      "Possessivbegleiter": [["mein Freund", "mi amigo"], ["meine Freunde", "mis amigos"], ["unser Freund", "nuestro amigo"], ["unsere Freundin", "nuestra amiga"], ["eure Freunde", "vuestros amigos"], ["ihr Freund", "su amigo"]],
      "mucho / poco": [["viel Verkehr", "mucho tráfico"], ["viele Leute", "mucha gente"], ["viele Hotels", "muchos hoteles"], ["wenige Läden", "pocas tiendas"]],
      "poder": [["yo", "puedo"], ["tú", "puedes"], ["él/ella", "puede"], ["nosotros/as", "podemos"], ["vosotros/as", "podéis"], ["ellos/as", "pueden"]],
      "Modalverben": [["Wir können morgen bleiben.", "Podemos quedar mañana."], ["Ich will nicht ins Café gehen.", "No quiero ir al café."], ["Du musst viele Dinge machen.", "Tienes que hacer muchas cosas."]],
      "ir": [["yo", "voy"], ["tú", "vas"], ["él/ella", "va"], ["nosotros/as", "vamos"], ["vosotros/as", "vais"], ["ellos/as", "van"]],
      "hacer": [["yo", "hago"], ["tú", "haces"], ["él/ella", "hace"], ["nosotros/as", "hacemos"], ["vosotros/as", "hacéis"], ["ellos/as", "hacen"]]
    }
  }
};
